name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # REPLACE 'YOUR_HF_USERNAME' and 'YOUR_SPACE_NAME' below with your actual Hugging Face details
        run: git push https://Yash-77:$HF_TOKEN@huggingface.co/spaces/Yash-77/LeafSense main
